import z from "zod";

const healthMetadataSchema = z
	.object({
		id: z.uuid().optional().openapi({
			description: "Ephemeral identifier for the Cloudflare Worker runtime instance or request",
			example: "550e8400-e29b-41d4-a716-446655440000",
		}),

		tag: z.string().optional().openapi({
			description: "Cloudflare service tag (environment, deployment, colo, or build identifier)",
			example: "prod-fra-01",
		}),

		timestamp: z.iso.datetime().optional().openapi({
			description: "Timestamp generated by the Cloudflare Worker runtime (ISO 8601)",
			example: "2024-01-01T00:00:00.000Z",
		}),
	})
	.openapi({
		description:
			"Cloudflare Worker service metadata. All fields are optional and may vary between requests.",
	});

export const healthSchema = z.object({
	status: z.string().openapi({
		example: "ok",
		description: "Health status of the service",
	}),
	timestamp: z.string().openapi({
		example: "2024-01-01T00:00:00.000Z",
		description: "Current server timestamp in ISO 8601 format",
	}),
	metadata: healthMetadataSchema,
});
