/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ProtectedLayoutRouteImport } from './routes/_protectedLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedLayoutTracesRouteImport } from './routes/_protectedLayout/traces'
import { Route as ProtectedLayoutSettingsRouteImport } from './routes/_protectedLayout/settings'
import { Route as ProtectedLayoutPixelsRouteImport } from './routes/_protectedLayout/pixels'
import { Route as ProtectedLayoutMapRouteImport } from './routes/_protectedLayout/map'
import { Route as ProtectedLayoutIntegrationsRouteImport } from './routes/_protectedLayout/integrations'
import { Route as ProtectedLayoutEventsRouteImport } from './routes/_protectedLayout/events'
import { Route as ProtectedLayoutDomainsRouteImport } from './routes/_protectedLayout/domains'
import { Route as ProtectedLayoutCampaignsRouteImport } from './routes/_protectedLayout/campaigns'
import { Route as ProtectedLayoutApiKeysRouteImport } from './routes/_protectedLayout/api-keys'
import { Route as ProtectedLayoutAnalyticsRouteImport } from './routes/_protectedLayout/analytics'
import { Route as ProtectedLayoutAdminRouteImport } from './routes/_protectedLayout/admin'
import { Route as AuthLayoutSignInRouteImport } from './routes/_authLayout/sign-in'
import { Route as ProtectedLayoutSettingsUsageRouteImport } from './routes/_protectedLayout/settings.usage'
import { Route as ProtectedLayoutSettingsProfileRouteImport } from './routes/_protectedLayout/settings.profile'
import { Route as ProtectedLayoutSettingsAppearanceRouteImport } from './routes/_protectedLayout/settings.appearance'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protectedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutTracesRoute = ProtectedLayoutTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutSettingsRoute = ProtectedLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutPixelsRoute = ProtectedLayoutPixelsRouteImport.update({
  id: '/pixels',
  path: '/pixels',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutMapRoute = ProtectedLayoutMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutIntegrationsRoute =
  ProtectedLayoutIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutEventsRoute = ProtectedLayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutDomainsRoute = ProtectedLayoutDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutCampaignsRoute =
  ProtectedLayoutCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutApiKeysRoute = ProtectedLayoutApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutAnalyticsRoute =
  ProtectedLayoutAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutAdminRoute = ProtectedLayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const AuthLayoutSignInRoute = AuthLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const ProtectedLayoutSettingsUsageRoute =
  ProtectedLayoutSettingsUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => ProtectedLayoutSettingsRoute,
  } as any)
const ProtectedLayoutSettingsProfileRoute =
  ProtectedLayoutSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProtectedLayoutSettingsRoute,
  } as any)
const ProtectedLayoutSettingsAppearanceRoute =
  ProtectedLayoutSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => ProtectedLayoutSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof AuthLayoutSignInRoute
  '/admin': typeof ProtectedLayoutAdminRoute
  '/analytics': typeof ProtectedLayoutAnalyticsRoute
  '/api-keys': typeof ProtectedLayoutApiKeysRoute
  '/campaigns': typeof ProtectedLayoutCampaignsRoute
  '/domains': typeof ProtectedLayoutDomainsRoute
  '/events': typeof ProtectedLayoutEventsRoute
  '/integrations': typeof ProtectedLayoutIntegrationsRoute
  '/map': typeof ProtectedLayoutMapRoute
  '/pixels': typeof ProtectedLayoutPixelsRoute
  '/settings': typeof ProtectedLayoutSettingsRouteWithChildren
  '/traces': typeof ProtectedLayoutTracesRoute
  '/settings/appearance': typeof ProtectedLayoutSettingsAppearanceRoute
  '/settings/profile': typeof ProtectedLayoutSettingsProfileRoute
  '/settings/usage': typeof ProtectedLayoutSettingsUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof AuthLayoutSignInRoute
  '/admin': typeof ProtectedLayoutAdminRoute
  '/analytics': typeof ProtectedLayoutAnalyticsRoute
  '/api-keys': typeof ProtectedLayoutApiKeysRoute
  '/campaigns': typeof ProtectedLayoutCampaignsRoute
  '/domains': typeof ProtectedLayoutDomainsRoute
  '/events': typeof ProtectedLayoutEventsRoute
  '/integrations': typeof ProtectedLayoutIntegrationsRoute
  '/map': typeof ProtectedLayoutMapRoute
  '/pixels': typeof ProtectedLayoutPixelsRoute
  '/settings': typeof ProtectedLayoutSettingsRouteWithChildren
  '/traces': typeof ProtectedLayoutTracesRoute
  '/settings/appearance': typeof ProtectedLayoutSettingsAppearanceRoute
  '/settings/profile': typeof ProtectedLayoutSettingsProfileRoute
  '/settings/usage': typeof ProtectedLayoutSettingsUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_protectedLayout': typeof ProtectedLayoutRouteWithChildren
  '/debug': typeof DebugRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/_authLayout/sign-in': typeof AuthLayoutSignInRoute
  '/_protectedLayout/admin': typeof ProtectedLayoutAdminRoute
  '/_protectedLayout/analytics': typeof ProtectedLayoutAnalyticsRoute
  '/_protectedLayout/api-keys': typeof ProtectedLayoutApiKeysRoute
  '/_protectedLayout/campaigns': typeof ProtectedLayoutCampaignsRoute
  '/_protectedLayout/domains': typeof ProtectedLayoutDomainsRoute
  '/_protectedLayout/events': typeof ProtectedLayoutEventsRoute
  '/_protectedLayout/integrations': typeof ProtectedLayoutIntegrationsRoute
  '/_protectedLayout/map': typeof ProtectedLayoutMapRoute
  '/_protectedLayout/pixels': typeof ProtectedLayoutPixelsRoute
  '/_protectedLayout/settings': typeof ProtectedLayoutSettingsRouteWithChildren
  '/_protectedLayout/traces': typeof ProtectedLayoutTracesRoute
  '/_protectedLayout/settings/appearance': typeof ProtectedLayoutSettingsAppearanceRoute
  '/_protectedLayout/settings/profile': typeof ProtectedLayoutSettingsProfileRoute
  '/_protectedLayout/settings/usage': typeof ProtectedLayoutSettingsUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/docs'
    | '/privacy'
    | '/sign-in'
    | '/admin'
    | '/analytics'
    | '/api-keys'
    | '/campaigns'
    | '/domains'
    | '/events'
    | '/integrations'
    | '/map'
    | '/pixels'
    | '/settings'
    | '/traces'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/docs'
    | '/privacy'
    | '/sign-in'
    | '/admin'
    | '/analytics'
    | '/api-keys'
    | '/campaigns'
    | '/domains'
    | '/events'
    | '/integrations'
    | '/map'
    | '/pixels'
    | '/settings'
    | '/traces'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/usage'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/_protectedLayout'
    | '/debug'
    | '/docs'
    | '/privacy'
    | '/_authLayout/sign-in'
    | '/_protectedLayout/admin'
    | '/_protectedLayout/analytics'
    | '/_protectedLayout/api-keys'
    | '/_protectedLayout/campaigns'
    | '/_protectedLayout/domains'
    | '/_protectedLayout/events'
    | '/_protectedLayout/integrations'
    | '/_protectedLayout/map'
    | '/_protectedLayout/pixels'
    | '/_protectedLayout/settings'
    | '/_protectedLayout/traces'
    | '/_protectedLayout/settings/appearance'
    | '/_protectedLayout/settings/profile'
    | '/_protectedLayout/settings/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  DebugRoute: typeof DebugRoute
  DocsRoute: typeof DocsRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protectedLayout': {
      id: '/_protectedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protectedLayout/traces': {
      id: '/_protectedLayout/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof ProtectedLayoutTracesRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/settings': {
      id: '/_protectedLayout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedLayoutSettingsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/pixels': {
      id: '/_protectedLayout/pixels'
      path: '/pixels'
      fullPath: '/pixels'
      preLoaderRoute: typeof ProtectedLayoutPixelsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/map': {
      id: '/_protectedLayout/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof ProtectedLayoutMapRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/integrations': {
      id: '/_protectedLayout/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof ProtectedLayoutIntegrationsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/events': {
      id: '/_protectedLayout/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof ProtectedLayoutEventsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/domains': {
      id: '/_protectedLayout/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof ProtectedLayoutDomainsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/campaigns': {
      id: '/_protectedLayout/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof ProtectedLayoutCampaignsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/api-keys': {
      id: '/_protectedLayout/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ProtectedLayoutApiKeysRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/analytics': {
      id: '/_protectedLayout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedLayoutAnalyticsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/admin': {
      id: '/_protectedLayout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedLayoutAdminRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_authLayout/sign-in': {
      id: '/_authLayout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthLayoutSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_protectedLayout/settings/usage': {
      id: '/_protectedLayout/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof ProtectedLayoutSettingsUsageRouteImport
      parentRoute: typeof ProtectedLayoutSettingsRoute
    }
    '/_protectedLayout/settings/profile': {
      id: '/_protectedLayout/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ProtectedLayoutSettingsProfileRouteImport
      parentRoute: typeof ProtectedLayoutSettingsRoute
    }
    '/_protectedLayout/settings/appearance': {
      id: '/_protectedLayout/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof ProtectedLayoutSettingsAppearanceRouteImport
      parentRoute: typeof ProtectedLayoutSettingsRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutSignInRoute: typeof AuthLayoutSignInRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutSignInRoute: AuthLayoutSignInRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface ProtectedLayoutSettingsRouteChildren {
  ProtectedLayoutSettingsAppearanceRoute: typeof ProtectedLayoutSettingsAppearanceRoute
  ProtectedLayoutSettingsProfileRoute: typeof ProtectedLayoutSettingsProfileRoute
  ProtectedLayoutSettingsUsageRoute: typeof ProtectedLayoutSettingsUsageRoute
}

const ProtectedLayoutSettingsRouteChildren: ProtectedLayoutSettingsRouteChildren =
  {
    ProtectedLayoutSettingsAppearanceRoute:
      ProtectedLayoutSettingsAppearanceRoute,
    ProtectedLayoutSettingsProfileRoute: ProtectedLayoutSettingsProfileRoute,
    ProtectedLayoutSettingsUsageRoute: ProtectedLayoutSettingsUsageRoute,
  }

const ProtectedLayoutSettingsRouteWithChildren =
  ProtectedLayoutSettingsRoute._addFileChildren(
    ProtectedLayoutSettingsRouteChildren,
  )

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutAdminRoute: typeof ProtectedLayoutAdminRoute
  ProtectedLayoutAnalyticsRoute: typeof ProtectedLayoutAnalyticsRoute
  ProtectedLayoutApiKeysRoute: typeof ProtectedLayoutApiKeysRoute
  ProtectedLayoutCampaignsRoute: typeof ProtectedLayoutCampaignsRoute
  ProtectedLayoutDomainsRoute: typeof ProtectedLayoutDomainsRoute
  ProtectedLayoutEventsRoute: typeof ProtectedLayoutEventsRoute
  ProtectedLayoutIntegrationsRoute: typeof ProtectedLayoutIntegrationsRoute
  ProtectedLayoutMapRoute: typeof ProtectedLayoutMapRoute
  ProtectedLayoutPixelsRoute: typeof ProtectedLayoutPixelsRoute
  ProtectedLayoutSettingsRoute: typeof ProtectedLayoutSettingsRouteWithChildren
  ProtectedLayoutTracesRoute: typeof ProtectedLayoutTracesRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutAdminRoute: ProtectedLayoutAdminRoute,
  ProtectedLayoutAnalyticsRoute: ProtectedLayoutAnalyticsRoute,
  ProtectedLayoutApiKeysRoute: ProtectedLayoutApiKeysRoute,
  ProtectedLayoutCampaignsRoute: ProtectedLayoutCampaignsRoute,
  ProtectedLayoutDomainsRoute: ProtectedLayoutDomainsRoute,
  ProtectedLayoutEventsRoute: ProtectedLayoutEventsRoute,
  ProtectedLayoutIntegrationsRoute: ProtectedLayoutIntegrationsRoute,
  ProtectedLayoutMapRoute: ProtectedLayoutMapRoute,
  ProtectedLayoutPixelsRoute: ProtectedLayoutPixelsRoute,
  ProtectedLayoutSettingsRoute: ProtectedLayoutSettingsRouteWithChildren,
  ProtectedLayoutTracesRoute: ProtectedLayoutTracesRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  DebugRoute: DebugRoute,
  DocsRoute: DocsRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
